# -*- coding: utf-8 -*-
"""inference

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m5zXTE5VReTMYZB569HbrK2MWHWxkGDL
"""

import torch
import torch.nn as nn
import numpy as np

class CreditScoringModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(10, 16),
            nn.ReLU(),
            nn.Linear(16, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)


def main():
    model = CreditScoringModel()

    # Загружаем state_dict
    state_dict = torch.load("model/model.pt", map_location="cpu")
    model.load_state_dict(state_dict)

    model.eval()

    # Тестовый инференс
    x = torch.randn(1, 10)
    with torch.no_grad():
        y = model(x)

    print("Inference OK, output:", y.numpy())


if __name__ == "__main__":
    main()